name: CI on macOS

on:
  push:
    branches: ["main"]
    paths:
      - 'nue/mlx/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/mlx.yml'
  pull_request:
    branches: ["main"]
    paths:
      - 'nue/mlx/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/mlx.yml'

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Cache Python virtual environment
        uses: actions/cache@v4
        id: cache-venv
        with:
          path: ./.venv
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-uv-${{ hashFiles('./uv.lock') }}

      - name: Install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: uv sync --extra mlx

      - name: Run checks
        run: |
          uv run pyright ./nue/mlx
          uv run ruff check nue/mlx

      - name: Run tests
        run: uv run pytest ./nue/mlx
